services:
  - type: web
    name: playfriend
    runtime: python
    plan: free
    buildCommand: 'bash ./render-build.sh; pip install -r ./requirements.txt'
    startCommand: 'export PATH="/opt/render/project/.render/chrome/opt/google/chrome:$PATH"; echo "Current PATH: $PATH"; export TZ="America/Los_Angeles"; honcho -f ProcfileHoncho start'
    envVars:
     - key: DISCORD_TOKEN
       sync: false
     - key: MONGODB_URI
       sync: false
     - key: PYTHON_VERSION
       sync: false
     - key: UPTIME_ROBOT_API_KEY
       sync: false