services:
  - type: web
    name: playfriend
    runtime: python
    plan: free
    buildCommand: "bash ./render-build.sh; export PATH=\"${PATH}:/opt/render/project/.render/chrome/opt/google/chrome\""
    startCommand: "python app.py -p $PORT; python playfriend.py"
    envVars:
     - key: DISCORD_TOKEN
       sync: false
     - key: MONGODB_URI
       sync: false
     - key: PYTHON_VERSION
       value: 3.11.9
     - key: UPTIME_ROBOT_API_KEY
       sync: false